### PR TITLE
Core 252

### PR DESCRIPTION
**Pull request by rorticus**
**Type:** feature

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] Unit or Functional tests are included in the PR

**Description:**

This is the other half of removing streams from dojo/core . This cannot be merged until the [request library changes](https://github.com/dojo/core/pull/261) are merged into dojo/core!

Resolves #core-252

### CODE REVIEW

**Comment by rorticus** [comment]
(note that these tests are going to fail until we've got the dojo/core PR merged)

**Review by dylans — APPROVED** [review]

**Comment by rorticus** [comment]
`request` changes landed in core, just need it released!

**Comment by agubler** [comment]
Assume we can bump to latest core version and this would be ready?

**Comment by rorticus** [comment]
Good to go!

**Review by agubler — APPROVED** [review]

**Pull request merged**
